normals_estimation:
  max_radius: 1.0
  max_nn: 30

orth_planes_extraction:
  min_clust_size: 10
  affinity: "cosine"
  dist_threshold: 1.0e-1

  from_pc: "first"  # "middle"
  downsample:
    use: False
    voxel_size: 0.6
    upsample: False

# planes_extraction:
planes_segmentation:
  # algo: "svd_filter"
  algo: "spvcnn"

  spvcnn:
    voxel_size: 0.05
  # svd_filter:

metrics:
  mom:
    min_nn: 6
    input: "planes"  # "whole"
  mean_map_metric:
    min_nn: 6

dataset:
  name: "carla"
  refine_ts: False
